name: Run Tests

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/*.yml'
      - 'server/*.py'
      - 'server/*.yml'
      - 'plugins/src/**'
      - 'plugins/test/**'
      - 'src/**'
      - 'test/**'
      - '*.ini'
      - '*.py'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install packages
        run: |
          python -m pip install .[dev]
          python -m pip install plugins/.[optional]
          python -m pip install -r server/requirements.txt
      - name: Invoke Tests
        run: pytest -c pytest-all.ini
      - uses: codecov/codecov-action@v3
        with:
          files: ./htmlcov-all/coverage.xml
